version: '3.8'

services:
  fastapi:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8989:8989"
    volumes:
      - shared-models:/app/models  # Usar volumen compartido para los modelos
    depends_on:
      - jupyterlab

  jupyterlab:
    build: ./jupyterlab
    container_name: jupyter_lab
    volumes:
      - shared-data:/data  # Volumen compartido para datos
      - shared-models:/models  # Volumen compartido para modelos
    ports:
      - "8888:8888"

volumes:
  shared-models:  # Volumen para almacenar modelos
  shared-data:  # Volumen para almacenar datos
